version: '3.7'

services:
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_AUTH_GENERIC_OAUTH_ENABLED=true
      - GF_AUTH_GENERIC_OAUTH_NAME=OAuth
      - GF_AUTH_GENERIC_OAUTH_ALLOW_SIGN_UP=true
      - GF_AUTH_GENERIC_OAUTH_CLIENT_ID=grafana
      - GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET=valid
      - GF_AUTH_GENERIC_OAUTH_SCOPES=email profile
      - GF_AUTH_GENERIC_OAUTH_AUTH_URL=http://localhost:5050/oauth/authorize
      - GF_AUTH_GENERIC_OAUTH_TOKEN_URL=http://host.docker.internal:5050/oauth/token
      - GF_AUTH_GENERIC_OAUTH_API_URL=http://host.docker.internal:5050/userinfo
      - GF_SERVER_ROOT_URL=http://localhost:3000
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    networks:
      - my_network

networks:
  my_network:
    driver: bridge